FROM php:8.3.31-fpm AS app

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y \
  git \
  unzip \
  zip \
  libzip-dev \
  libicu-dev

RUN docker-php-ext-install pdo pdo_mysql zip intl

ENV COMPOSER_ALLOW_SUPERUSER=1

COPY --from=composer:2.8.4 /usr/bin/composer /usr/bin/composer

COPY --chown=www-data:www-data src/composer.* ./
COPY --chown=www-data:www-data src/Modules ./Modules

RUN composer install --prefer-dist --no-scripts --no-progress --no-interaction

COPY --chown=www-data:www-data src ./

RUN composer dump-autoload --optimize
