# Node
FROM node:20-alpine AS frontend

WORKDIR /app

COPY src/package*.json ./

RUN npm ci

COPY src/ ./

RUN npm run build

# PHP
FROM php:8.3.31-fpm AS app

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y \
  git \
  unzip \
  zip \
  libzip-dev \
  libicu-dev

RUN docker-php-ext-install pdo pdo_mysql zip intl

ENV COMPOSER_ALLOW_SUPERUSER=1

COPY --from=composer:2.8.4 /usr/bin/composer /usr/bin/composer

COPY --chown=www-data:www-data src/composer.* ./

RUN composer install --no-dev --prefer-dist --no-scripts --no-progress --no-interaction

COPY --chown=www-data:www-data src/ ./
COPY --chown=www-data:www-data --from=frontend /app/public/build ./public/build

RUN composer dump-autoload --optimize

# Nginx
FROM nginx:1.31.0-alpine-slim AS web

COPY nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

COPY src/public /var/www/html/public

COPY --from=frontend /app/public/build /var/www/html/public/build