services:
  web:
    build:
      dockerfile: Dockerfile.prod
      target: web
    ports:
      - '80:80'
    depends_on:
      - app

  app:
    build:
      dockerfile: Dockerfile.prod
      target: app
    depends_on:
      - db

  db:
    image: mysql:9.1.0
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - '127.0.0.1:3306:3306' # Expose MySQL only to the host machine
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

volumes:
  mysqldata:
