on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: gh-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.RELEASE_PLEASE_BOT_APP_ID }}
          private-key: ${{ secrets.RELEASE_PLEASE_BOT_APP_PRIVATE_KEY }}

      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v5
        with:
          token: ${{ steps.gh-token.outputs.token }}
          release-type: simple
